const db = require('APP/db')

const seedUsers = () => db.Promise.map([
  {name: 'Jane Smith', email: 'jane@example.gov', password: '1234', sleepDebt: 15.70, averageSleep: 8.5},
  {name: 'Aly Khaya', email: 'aly@example.gov', password: '1234', averageSleep: 8.3, sleepDebt: 4.30},
  {name: 'Chloe Hwang', email: 'chloe@example.gov', password: '1234', averageSleep: 7, sleepDebt: 4.10},
  {name: 'Laura Jeong', email: 'laura@example.gov', password: '1234', averageSleep: 7.5, sleepDebt: 3.30},

], user => db.model('users').create(user))


const seedDreams = () => db.Promise.map([
  {title: 'A Bad Dream',
  content: 'Pictures that can’t be described\nDance in the brilliance\nFor you will never be outnumbered\nA celestial body enters\nHope will show you\nHorizons of magnificence\nBecome what is',
  isPublic: true,
  dreamType: 'Recurring Dream',
  sleepStartHour: 23,
  sleepStartMinute: 59,
  sleepEndHour: 5,
  sleepEndMinute: 50,
  date: '2017-3-30',
  user_id: 1},
   {title: 'Reconciling with Ex',
  content: "In the dream, I was in my living room and I looked out the window and it was cloudy. I saw that my ex moved in with a couple of things and he told me how he lied he was going to be homeless so my tenants upstairs decided for him to move in with them. I was so angry. He was wearing white shirt and gray pants. He was also walking bare feet in the house. So I ran into my dad who was in my kitchen. He's cooking soup. He said its for my ex and I told him my ex is stalking me. All of the sudden my ex broken my ceiling and I can see him standing above. He's telling me how angry he was to see me out with my boyfriend and how he watched me had sex. He said how it kills him to hear me moan. So I freaked out. I went upstairs and it was empty but I told my tenants not to believe him but they think I'm rude. Now, I am pulling him out and he refused to move. I cried and told my dad. All of the sudden we are at his job building. Now, I am pulling him out and he refused to move. I cried and told my dad. All of the sudden we are at his job building. He told me I'd be safe in here. I asked him how long do I have to hide in here. When I went back to my house, my ex tampered with my medication and my dads. I started to tell my mom I'm not taking my medication. I freaked out. I was going to call my boyfriend but it felt like he was far from reach. I didn't want him to be angry either. I felt like my mom and dad was no help. I had to try to pull my ex out. So I told my ex to come out right now. He came down the stairs shouting. My head started to hurt. He's cursing me out. He brought down a plastic dish. Then wore his flip flops by the door (now I remember I got flip flops by the door that my bf got me). I told my ex to get out. He was stubborn to leave. I got mad and he got even madder. I try to push him out and he won't leave. I was so terrorized. When I almost got him out the door, I woke up with neck pains and headaches.",
  isPublic: true,
  dreamType: 'Recurring Dream',
  sleepStartHour: 22,
  sleepStartMinute: 23,
  sleepEndHour: 6,
  sleepEndMinute: 39,
  date: '2017-3-29',
  user_id: 1},
   {title: 'Hurt Dogs',
  content: "The first night my dog Scarlett was in my yard and there was a bonfire. There was barbed wire around the fire so no one would get too close. Scarlett became entangled in the barbed wire and caught fire. I went to help her. My other dog Stella got in my way so I shoved her away and it broke her leg. Both dogs seemed okay and I woke up but I was upset. Tonight a friend and I were in my yard and opened the gate to leave, Scarlett ran into the front yard and we chased her to get a leash on her. She then ran into the main road as I called for her to stop. Stella followed her and they ran through an intersection. Scarlett made it past the cars but Stella was hit very hard. She walked back to me and I woke up and cried.",
  isPublic: true,
  dreamType: 'Nightmare',
  sleepStartHour: 21,
  sleepStartMinute: 59,
  sleepEndHour: 7,
  sleepEndMinute: 9,
  date: '2017-3-28',
  user_id: 1},
   {title: 'Smoke/Summer/Beach',
  content: 'I saw that I was inside a house with others. I could see from the window the sea and the sunny sky. Then further away I saw lot of smoke (probably coming out of a building). It filled the sky. It was dark brown and dense. The smoke was coming towards us. We saw it and stayed in. I could also see a helicopter above the sea but flying very low because of the smoke. The smoke covered the place now. I was holding my mobile in case it would get very dark so I could use it for light in case I would get scared of the dark. But the smoke lasted only for seconds. It left us. The sky was clear now. There was a lot of light from the sun now. It was day time and summer. The helicopter landed on the sea but in the shallow water. Now I saw myself walking on the beach wearing my white swimsuit. I was relaxed. I noticed that there was some sand on my body. And I think I was barefoot.',
  isPublic: true,
  dreamType: 'Lucid Dream',
  sleepStartHour: 23,
  sleepStartMinute: 2,
  sleepEndHour: 4,
  sleepEndMinute: 40,
  date: '2017-3-27',
  user_id: 1},
  {title: 'Carnival of Terror',
  content: 'I dreamt I was at a carnival/fair type of place. I was hanging out with friends, I remember anon and anon 2 being with me. The tip of my left index finger was bothering me, one time I looked down and saw something grey sticking out of it. The grey object began to grow out of my finger, it looked like a piece of pencil led for a mechanical pencil. I remember feeling pain as this was happening. After about an inch of it grew out of my finger it fell off, this was followed by a bunch of yellow tinged puss pouring out the exit hole that the grey object created. Pain was still relevant. After about a minute it stopped. I cleaned up my finger and headed toward a line of people. Following the line I ended up in a dance/concert type of event where I saw anon 3 and anon 4. Two people I never see, one I haven’t seen in years. I left the place after someone tried getting me to dance and I wouldn’t.',
  isPublic: false,
  dreamType: 'Nightmare',
  sleepStartHour: 20,
  sleepStartMinute: 49,
  sleepEndHour: 8,
  sleepEndMinute: 8,
  date: '2017-3-26',
  user_id: 1},
  {title: 'Peach Creature',
  content: "The creature I am seeing has peach colored skin, is bald, and it’s back legs fold inward at the knees. It uses them as sort of a catapult which enables it to launch itself long distances in a single bound. It’s face is demonic looking with small eyes, a wide stretching mouth with big jagged looking teeth. The scenery is a glowing red in the night sky, I am in a village with no lights anywhere to be seen. The creature enters the village.. the next thing I remember is seeing a baby held within the creatures short front legs. The creature then continues going to every house in the village and repeating this till every baby in the village has perished, the creature stained blood red when finished. After this, I remember perceiving the village as if I were laying down on the ground outside, on my back staring into the red night sky. A woman walks into my view.",
  isPublic: false,
  dreamType: 'Recurring Dream',
  sleepStartHour: 23,
  sleepStartMinute: 1,
  sleepEndHour: 8,
  sleepEndMinute: 31,
  date: '2016-3-25',
  user_id: 1},
   {title: 'Shopping at Satan\'s Jewelry Store',
  content: "I am back in East Liverpool, and am visiting Calcutta, where all the better stores are. I see a well lit store, neon on the front, and sparkling of many colors inside of the store. I walk inside out of curiosity. What is Satan selling these days? Is it actual Satanism, or some kind of fad of dark imagery? The sign out front, said in bright blue and pink lettering, “Satanism Store”. I look around and see display cases of sparking jewelry made of precious stones of all colors. I catch a partial glimpse of a pentagram hidden behind a display case. All in all, it seems like a mix of high end jewelry store and some kind of hand metal craft of metal jewelry with different bold designs that seem ancient pagan inspired. I walk pass the jewelry. I believe it is unaffordable, but I do not see any prices. and I am not interested in Satanism, the sparkling jewelry, was some how Satanic, but not openly Satanic, but is jewelry crafted by Satanists for other Satanists. An elderly lady comes up to me and says “I know just what you are looking for, come, let me show what we have back here” She leads me a small shelf full of Mary statues. They look like the miniature versions of the Mary statue at the church I attend. She then shows me a beautiful collection of polished stones: all colors of onyx, there's periodot (green), green aventine, colors of blue, orange, and red. She says, 'See all these beautiful natural stones?' She points out one flat, polished, blue white stone on display she says, 'but this is your stone, because you have Native American blood from which you get your psychic abilities from flowing through your veins.' That stone, I realize must be celestite.",
  isPublic: true,
  dreamType: 'Recurring Dream',
  sleepStartHour: 23,
  sleepStartMinute: 59,
  sleepEndHour: 6,
  sleepEndMinute: 0,
  date: '2017-3-24',
  user_id: 1},
   {title: 'Queen\'s Sister',
  content: "I saw that I wanted to paint the gate doors of my house. I was supposed to be a queen even though I was no different than I usually am (clothes or appearance or time). Two men were instructing me how to do it. I was holding a brush and I was just using water to practice. I noticed some dust while doing it. They said that I would need help because I have a busy life and did not have a lot of time to do it. I was looking at the gate doors and I thought that they were't big and I could paint them on my own. I could finish in a couple of hours. The color I wanted to paint them was dark blue. Navy blue I guess. The present color is grey and I wanted to refresh it with the blue. Then I was told that my sister who was also Queen (but I was in charge) would not help cause she thought qeens do not do this kind of things. I told them to tell her to come. I saw her coming down from the stairs to me. She was wearing a dress of old age (victorian I guess). She also had a mustache. I did not comment her mustache even though I've noticed it. I told her to paint with me the door gates and work is not a shame. It doesn't matter if we are queens or not. She said that the reason she was not helping was because the gates are wet cause it rained and need to dry first. I looked at them and she was right, they were wet, but I did not admit it and said maybe we can put the primer first. Somehow I wanted her to stay just in case she was trying to find excuses. I also feel that I was in a hurry to start. Someone has already put blue paint on them but it was unfinished and I was asking who did it. I think it was a child. A boy... That's all I remember even though the dream did not finish there.",
  isPublic: true,
  dreamType: 'Lucid Dream',
  sleepStartHour: 23,
  sleepStartMinute: 2,
  sleepEndHour: 7,
  sleepEndMinute: 40,
  date: '2017-3-23',
  user_id: 1},
  {title: 'Death Warning',
  content: "So I had a few dream of the world ending and as I gathered my family to take them to a safe place I found myself frantically looking for my older brother to take him with us when we all finally make it to a safe place my a big wave comes and takes my little brother away and I try so hard to save him and I can't my other dreams are similar end of the world scenario but in my dreams my little brothers family are in my dreams and although I'm very close to my little brother i do not have a good relationship with his father or his family and we do not comunícate .....sadly my little brother just passed away very unexpected and I am wondering why before it happened I kept having all those dreams it's not the first time I dream of things or people and have things happen ....I am actually worried because I am now having dreams of being in car accident or seeing car accidents and last night I had a dream of being cought in a storm while hosting a party but I had a very uneasy feeling in my dream and I've had that same feeling all day",
  isPublic: false,
  dreamType: 'Nightmare',
  sleepStartHour: 22,
  sleepStartMinute: 49,
  sleepEndHour: 5,
  sleepEndMinute: 58,
  date: '2017-3-22',
  user_id: 1},
  {title: 'Swimming Away from Albino Python',
  content: "So I was at the Sunshine Coast with a dream friend or two. The city was extremely modern and spacious. There appeared a man made beach with the edge being one step in with the water level unknown. The step made of a common grey speckled bricks with newer houses. I walk along it looking for a good place to enter the water. After a long walk the brick turns to a natural sand. There is more people there some I knew from high school. The atmosphere is overall friendly. not long into the water is a smallish round sand island. I enter the water and swim around there are a few others there. I start to get more slightly to the side of the island because of a current but every thing is fine. After a little while I see two albino diamond pythons half submerged in the water and their heads resting on the slop of the island. I go to stand up in the water however my foot touches a albino diamond python that I can't see and I instantly raise my feet and swim a bit to avoid being bitten. I try again futher down the current but there are more pythons under the water everywhere. My only option is to allow the current to take me to the back half of the island but I don't want to go to the back of the Island and panic. I start to swim frantically towards the island however at this point the current is to strong and I'm not getting closer to the island. So I relax and keep paddling lightly. The sand behind me, the shore line, turns to a dark brown rocky pebble an older style like in brisbane. At half way a long the side of the island I see a short small round edge on the shore line. I reach for it and climb onto it. I need to get to the island and if I dive for it I could under dive and be taken by the current again or I could over dive and hurt myself in hitting the sand. I plan to dive with my face more upwards as to hopefully avoid injury. I do this and successfully reach the island with no problems. There is a crowd still on the island, it is once again a friendly and sunny atmosphere.",
  isPublic: false,
  dreamType: 'Recurring Dream',
  sleepStartHour: 20,
  sleepStartMinute: 49,
  sleepEndHour: 8,
  sleepEndMinute: 8,
  date: '2017-3-21',
  user_id: 1},
  {title: 'Ancient Ancestor',
  content: "I was in my room at dads house. Dad had left to go get paint in the morning and so my brother and I were home alone getting ready for school I think. I was in my room, sitting on the bed and my door was open wide, when I felt like someone was watching me. When I couldn't shake the feeling, I went to pierces room to ask him about it and he said he was fine, but then everything changed and I heard the voice of a ghost, it was the one I felt watching me in the hallway. She was African with really dark skin and moldy yellow teeth and knappy hair. She wore a raggedy white dress and i could only see and hear her at this point. Pierce had no idea what was going on. She said she had something important to tell me that couldnt wait and she insisted on being near pierce and touching him. Pierce had no idea what was going on as only I could see and hear her. Suddenly she touched pierce and I saw her for the first time in her physical form. I knew she was in pierces body but I saw her as a dark black woman in a raggedy white dress. She had short knappy hair and her teeth were rotten. She was angry she said and she wanted something. Suddenly it got almost pitch black in the room save for a projection of black people dying from slavery. I think she wanted revenge for it and she told me she need me. I got worried and tried to get her out of Pierces body but she just laughed and said it wouldn't work. She was a witch in her life and this made her a more powerful ghost apparently. Then she disappeared with pierces body as das came home and so I was alone. I tried telling dad but I was crying super hard and he didn't believe me. Then I woke up after saying I needed to tell my friends at school. ",
  isPublic: false,
  dreamType: 'Nightmare',
  sleepStartHour: 23,
  sleepStartMinute: 1,
  sleepEndHour: 8,
  sleepEndMinute: 31,
  date: '2016-3-02',
  user_id: 1},
   {title: 'Shopping at Satan\'s Jewelry Store',
  content: "i dreamt i was in a highly modified version of my home, it had a shrunken version of my hospital workspace inside of it along with a selection of other employees that i could have known in the distant past. a few of 'em were supervisory but relatively kind, and they tried to help me de-clutter my hopelessly cluttered place, except for one spot in the beginning of a hallway where there were electrical wires of some kind blocking me from traversing without hopping over them. i had a large metal cart of some kind filled with some kind of supplies i was to move from a bedroom into the living room, and i could only move the cart over to where the wires were, then unload it there, or it could have been i was to take clutter from the living room into the cart then shove it down the hallway and unload it into the bedroom. i went down the hall to the bedroom when a bee came out of nowhere and started harassing me, chasing me back and forth, and i picked up a white tennis shoe and started ineptly swinging at it trying to get it to flee, and missed each time until the final time where i swatted it good where its stinger was, and it mysteriously shattered into zillions of glittery sparkly pieces with a loud glass-shattering ZAP! then what was left of it instantly turned into a beautiful petite blonde beauty queen, who waved her finger at me  :nodding: and said \"what did you do that to me for?\" \"i want you to tell me, IN FRENCH, what you just did to me!\" and i struggled with my rudimentary french to try to grab a suitable word and only feebly came up with \"vomir\" [infinitive form of the verb meaning \"to vomit\"]. she laughed at me the way a pedantic french teacher might derisively laugh at a slow french student. but she was BEAUTIFUL!!! gorgeous, wearing light blue designer jeans and a white lace top. ice-blue eyes, angelic face which mop of blonde ringlets framed most alluringly. she then said, after some flirtation, \"all is forgiven, but first i need to find out how you really feel about me, let's have sex.\" then the dream jarringly segued into another scene where i was discussing fascism with an englishman. then i awoke.",
  isPublic: true,
  dreamType: 'Normal Dream',
  sleepStartHour: 21,
  sleepStartMinute: 59,
  sleepEndHour: 4,
  sleepEndMinute: 9,
  date: '2017-3-18',
  user_id: 1},
   {title: 'Invisible Creature',
  content: "I was in my house (a mix of 3-4 different real-life houses), I was at the kitchen stove. I was getting ready to cook something. Noticed plants were in oven. I heard a noise. Water running out of the sink faucet. Something invisible turned it back off. They moved a container holding utensils. Lifted a huge knife. Attempted to stab me in my neck. I screamed for my mom to help me. She was busy. Kept begging. (misunderstanding for some reason). I begged a few more times. She said she would be there in a few minutes. Invisible \"creature\" was way too strong. My strength failed. I was stabbed. (I made the blade hit slightly lower) Wound wasn't as bad as it could've been. I kicked the invisible creature backwards and ran into the room my mom was in. She was horrified to see the knife. I sarcastically thanked her for helping me. Told her to pull the knife out. I wrapped a towel tightly around my neck to stop bleeding. I could hear the creature coming. Told my mom we had to get out of the house. We ran outside, past our vehicles. Told her to take the car. She said it is better to run on foot. I had no shoes or socks on. Snow was on the ground. Severe frostbite and my feet stuck to the sidewalk and roadway as we ran (extremely painful) told her I had no shoes on. Had to warn my dad and two other family members to stay out of the house. Terrifying black shadowy creature stood in the doorway when I went back to the house. Then I realized it was just the lighting. It was one of my family members. I tried to warn them to stay outside, but they didn't. Followed them in. I found my dad and other family member already inside. I begged them to leave the house. Told them it was too dangerous to stay there. They refused. I knew I would have to leave them there. I believe I prayed for their safety and then I woke-up. ",
  isPublic: true,
  dreamType: 'Normal Dream',
  sleepStartHour: 23,
  sleepStartMinute: 2,
  sleepEndHour: 3,
  sleepEndMinute: 40,
  date: '2017-3-19',
  user_id: 1},
  {title: 'Friend Who Passed',
  content: "My friend Eli died 12 years ago when I was 14. He was a very happy, goofy, loving person. He always got picked on in school because he was kind of nerdy. He died suddenly and unexpectedly. The day he died he asked me if I wanted to come over and play video games, I said no, let’s do it tomorrow. I was tired. So I never got to go play with him and have always felt bad about it. I have not thought of Eli for a while, until last night when I dreamt this: Eli was still alive, and then he died. I felt very sad and cried really hard for a long time. He then came back to life, but only I could see him. He took me on a strange vacation. We were walking through this beautiful, bright, tropical place, with amazing plants I have never seen. There was a large cliff/wall and we both almost fell over it and were hanging on the edge, when someone saved us. And we kept walking through this tropical wonderland. When we arrived at our intended destination it was an underground hotel without any windows. We were told we had to shower before entering the hotel.and that once inside we would not be allowed to leave for 4 days. I was frightened by this and felt claustrophobic about being locked in an underground building. I said I didn’t want to go in there. Then I woke up. Feeling sadness and confusions. What does any of this mean?",
  isPublic: false,
  dreamType: 'Nightmare',
  sleepStartHour: 20,
  sleepStartMinute: 49,
  sleepEndHour: 5,
  sleepEndMinute: 8,
  date: '2017-3-25',
  user_id: 1},
  {title: 'Being Chased',
  content: "A really scary human with claws and sharp teeth was coming after me. She looked exactly like me, except for black hair and creepiness. She was wearing all black. I knew I was dreaming but was too terrified to face her. Although I initially attempted to ask her who she was. She screamed & charged towards me. Much later, I found this other girl in the bathroom. She also looked like me, but she had black hair. I told her I forgive her for some reason. She told me that was a lie. I admitted it and told her if it was someone else they would be forgiven. However, since you ARE me, I don't. She said she knows. I apologized for interrupting her. Wanted to know who and why the scary girl was after me before I woke-up. She was upset I interrupted her, & acted like she had no clue who I was talking about. For some reason, I mentioned the grudge. (Haven't watched any scary movies in YEARS though) Then she finally realized who I meant. She was getting ready to tell me, but I woke up anyway. What might that be about?",
  isPublic: false,
  dreamType: 'Recurring Dream',
  sleepStartHour: 23,
  sleepStartMinute: 49,
  sleepEndHour: 6,
  sleepEndMinute: 8,
  date: '2017-3-31',
  user_id: 1},
  {title: 'Crushing',
  content: "So everyone is \"Shipping\" me with this person, and I am not really sure if I like them or not. We are good friends and all, and about 3 weeks ago i had a \"good\" dream about them, though i can not remember it. THese past 3 nights I have had bad dreams. Last nights, I was house sitting with two others, when we got inside the house, Drake and Josh (yes) was swimming in the pool. They tried to basically run, but for some reason i tried to fight them. Then it was girls fighting us, and then they left when I called 911. 911 arrived and it was like a bunch of people. I was then told it was the person i am friends with in real life, and glare at him. He glares back, and says something like \"I never liked you\" and then I woke up. The night before was where we moved, but the dream didn't start until we were exploring our new town. My mom was not in the dream, but my other family was. THe ground was flat. I guess I was happy, until I saw this lap pool and remembered all my friends and the guy i am shipped with and got really sad (I am on a swim team, so lap pool makes sense). I usually don't ever have dreams so I find it kind of odd i have been in these past few days, especially all bad dreams, about this person.",
  isPublic: true,
  dreamType: 'Normal Dream',
  sleepStartHour: 20,
  sleepStartMinute: 49,
  sleepEndHour: 8,
  sleepEndMinute: 8,
  date: '2017-4-01',
  user_id: 1}, {title: 'Loki and Koriandr',
  content: "I dreamed of this super romantic setting of (Toms) Loki and a really beautiful, realistic iteration of Koriandr (also known as Starfire) go on a date and I was tagging along. They were in some grand, ornate room with pillars and a sunset in the distance - a place which I wish I lived in. Not a whole lot more to it than that. I was having a great time with them and felt happy. We played video games and drank mimosas! I felt great and didn't care if how long I was staying! The date went on and we went to watch a movie, and it was a very cheerful comedy movie. This was probably one of the most pleasant dreams I've ever had.",
  isPublic: false,
  dreamType: 'Normal Dream',
  sleepStartHour: 21,
  sleepStartMinute: 59,
  sleepEndHour: 7,
  sleepEndMinute: 50,
  date: '2017-4-02',
  user_id: 1}, {title: 'Bella Whose Name Was Dina',
  content: "this starts in a corridor or walkway of a building. it could be an underground tunnel of a train station platform. it could be a corridor in a university, or, it could be the walkway of the mater, from platt street to the second level of the mater, where the steps are, near the elevators. not sure i see her prior to this moment in the dream, but as i step down about 5 steps, i see ahead of me, going up 5 steps, is that young Bella woman. i see the back of her. she is about 2, maybe 3 metres ahead of me. as she goes up the steps, i see that she is holding hands with a young guy, who is on her left side. its her left hand, joined to his right hand. im a bit surprised by that, but, good for them.  he is wearing a cap (back to front), some tee, and a long pair or jeans, that cover his shoes. he looks like a skating character from a computer game. then, what could be, up the hill between bar beach, and the bar beach hilly carpark, im about to step past bella, or do so, but she stops me. she is to my right. it is daytime. we are on the footpath of memorial drive, just up the hill from the bar beach surf club building. the hilly carpark is to our left. the path we are on, also turns towards the beach itself, and along the hill of the carpark. although her name is bella, she tells me her name is Dina. i'm sure we can be friends.  i think she could be lying about her name (dont really know why she has to). she does ask me what my name is. because i'm a bit suspicious of her name, i simply say to her \"no, im not telling you\" or something like that. she could be a bit upset that i say that to her. i'm a little assertive when i say that. and then i keep walking, to perhaps cross the road of memorial drive, to go west, along parkway ave. i don't cross over but thats one option i have. or i can keep going up the hill, along side memorial drive, and not along the cliff side, of the carpark. well, i'd end up on the footpath of the cliff side eventually. then i look at my mobile phone. dad has possibly sent me an sms, or its supposedly from him, which is a guess. i try to read it. in the sms, there are three different business names. all three are related to price quotes for a task that needs to be done. the first business is not known to me, though i do read it. the second one is a car smash repair business. the third one is possibly the westdale corner shop. the message is like that of an advert in a newspaper but more like a personal note for me. oddly enough, i read my name at the end of the message. its an supposed sms from dad, with my name at the end of it.",
  isPublic: false,
  dreamType: 'Recurring Dream',
  sleepStartHour: 20,
  sleepStartMinute: 34,
  sleepEndHour: 6,
  sleepEndMinute: 9,
  date: '2017-3-03',
  user_id: 1}, {title: 'My sister\'s and I child star beatdown',
  content: "In my dream, I was at my middle school, working some kind of community service charity function for student council/this society I'm in. I was the ticket handler along with a friend. As we were in the front of the school by the entrance handing out food, drink, and raffle tickets, a person that I least expected to walked in. The person was Jonathan Lipnicki at his current age. My friend and I just looked at each other wide-eyed, but gave him his tickets that he paid for. After we were sure that everyone that wanted to attend was there, we both accompanied each other for the rest of our evening. Later on that evening, we bumped into him again and then my friend left me by myself with him. We started conversating and I stayed with him for the rest of the night instead. We kept talking, played a few games together, and then I got extremely mad at him for something and went home. Somehow he found out where I lived and came over with an apology and one of the games we were playing. I opened my room door to see him standing there, but slammed it again. I finally came out and forgave him and we continued to talk. We caught a bus somewhere, rode for about an hour talking, and he had to get off at a stop before me. Before getting off he said “ I love you”. I said it back and when he got off, everyone on the bus stared at me like “ What!?!”, then I woke up!",
  isPublic: false,
  dreamType: 'Lucid Dream',
  sleepStartHour: 22,
  sleepStartMinute: 49,
  sleepEndHour: 5,
  sleepEndMinute: 30,
  date: '2017-3-04',
  user_id: 2}, {title: 'Gift From Michael',
  content: "I was lying down in a church and felt strangly surprised. I also surprisingly felt very spiritual and wanted some wine for some odd reason. I searched and searched around every corner of my mind and was left exhausted and felt like in that moment i could die. Suddenly i was thrust into what i perceived to be an astral flight there among the Stars.Against the black the lights were blinding yet warm and beckoning,drawing me deeper into existing without breath,nor sound.just light and wonder and the power of Love. My feet wandered in places without form. My body was free,i felt a little shocked and immersed in light ... everything around me was love. There was someone there as my guide.i dont know who he was or if i had faith in him,however there he was in love and so was I. Only the moon knows just how long,but it seemed to be endless. Until he,my guide,said to me in what seemed to be the deepest loudest soothing,assuring voice.",
  isPublic: false,
  dreamType: 'Normal Dream',
  sleepStartHour: 22,
  sleepStartMinute: 57,
  sleepEndHour: 6,
  sleepEndMinute: 51,
  date: '2017-3-05',
  user_id: 2}, {title: 'Johnny Depp',
  content: "I was at a dinner table with some people still in 19th century and I was making a pot lock breakfast with eggs with vegetables in them, rice and beans mush, I asked everyone if they wanted pancakes and bacon and they said yes. I said I was trying to use all of the left over food from a party my family had that morning. Some kid at the table that looked like Danikan had put all of the eggs in a pan but they were uneven so I was very annoyed. The eggs were all piled up on top of each other so they were growing really tall so I shook them around and they evened out on the pan to make fried eggs but they were not spaced out right. Although I was stressing out and getting flustered, I was trying to get a bacon pan ready but there was too much grease in the pan so I was trying to dump half of it out in another pan, this made me feel so angry. The bacon I had was in the shape and size of sun dresses. I was angry that I could only fit three on the pan at a time but then I was confused as to why they were bacon dresses and then they were regular bacons again. My aunt walked in and was talking to my mom about her financial situation. She told her she must have been upset when I made all of the food because she can't afford it. My mom said she could when my aunt was living there. My aunt said well I'm back but I don't think my mom wanted her to be. My dad looked outside and said oh no hes back and asked me if I remembered the blank license plates. I remembered the man from earlier had blank license plates too. He said he thinks that the guy across the street is also in front of the house. I looked and it was this mime that was wearing a striped outfit but the stripes were orange and green and black. He said that he had heard a lady scream and a dog barking in the front of the house and he thought it was at that guy. I looked on the kitchen buffet table and there was an orange, green, and black striped outfit laying there. I started getting nervous and looked outside and saw an ocean in the background and remembered the flood and saw a vision of an orange and red storm in the clouds with a black eye in the center. Some girl at the table said at least hes pretty cute. Then someone else said no the cutest guy was Jonny Depp and I looked at her funny and fuming because I knew we were in the 19th century and Jonny Depp was supposed to be in the future. I thought what if he was a vampire and had really been alive in this time too.",
  isPublic: true,
  dreamType: 'Lucid Dream',
  sleepStartHour: 20,
  sleepStartMinute: 49,
  sleepEndHour: 8,
  sleepEndMinute: 8,
  date: '2017-3-06',
  user_id: 2}, {title: 'Bugs!!',
  content: "It was hot and humid and my house was infested with fleas, or at least what I thought were fleas! It was so hot I could barely think straight and I was dripping buckets of sweat, the bugs were 5X bigger than average fleas. They were still jumping around like fleas, hiding in the carpet, etc. There was flea repellent powder spread on every rug in the house. I see one crawling across my hand. They're FAST and they're huge - something isn't right! Next thing I know I see dozens of them crawling and jumping on my arms and legs, I'm running around trying to brush them off and kill them. Now there are hundreds crawling on my neck, face, arms and legs, they're getting inside my clothes, I'm panicking, I start to get an itchy burn everywhere. Next I realise they are going INTO my body. They are making their way under my skin and probably laying eggs and starting families inside of me, and I can feel all of it happening. I am numb with shock. I wake up!",
  isPublic: false,
  dreamType: 'Nightmare',
  sleepStartHour: 23,
  sleepStartMinute: 23,
  sleepEndHour: 6,
  sleepEndMinute: 41,
  date: '2017-3-06',
  user_id: 2}, {title: 'First Wild Experience',
  content: "My frst \"WILD\" (wake Enduced Lucid Dream) experience; I'm aware of falling asleep, but still being awake. I could hear the 4.30/5am birds outside. I've read up about WILD so thought I'd give it a go. I went into \"The Zone\" as I call it - the bit between being awake and being asleep - I was also aware of my partner beginning to waken beside me and hoped that wouldn't stop my process. I saw the patterns, but didn't think they were as strong as they've been before. I slipped into a dream state but was well aware of being awake still. I dreamed (although being totally lucid) I was getting into a little boat on the beach. I waved goodbye to someone I knew, but in real life I don't. I had a piece of bright yellow cardboard and kept holding it up to make sure this person could keep sight of me as I went om my journey. I kept shouting to this person 'bye for now' but they couldn't hear me. I tried to call their name, but couldn't remember it as in real life I didn't actually know who they were. I drifted off in the boat, round the corner out of sight of the beach, when I felt a touch scared. I began feeling like I was falling asleep, but knew I couldn't as I wouldn't remember the experience. As I slipped further into darkness, I had the loud buzzing in my ears and the vibrations which are the start of an OBE and I kind of freaked out thinking I'm not ready for this. At the same time, the alarm went off. I just wonder if I'd have relaxed into the situation as I've read I'm supposed to do I'd have had a perfect OBE.",
  isPublic: false,
  dreamType: 'Nightmare',
  sleepStartHour: 22,
  sleepStartMinute: 15,
  sleepEndHour: 8,
  sleepEndMinute: 12,
  date: '2017-3-07',
  user_id: 2}, {title: 'When I met Kate Winslet',
  content: "My dream starts out with me meeting my best friend from High school at her house for a sleep over. Then somehow, I end up at the local Grocery Store, by myself, with my mother, where I am flirting outrageoously with every man there. Then, My mom & I end up in this dim bookstore and my motheris off talking to someone. I come around the corner and Mom introduces me to this very plain woman with short messy dark hair named Maggie Kelly. Aparently this woman was a friend of my mother's and had placed an ad in a magazine to get pen pals and my mother had been trying to get me to write to her cuz she said we'd be good friends, we had a lot in common. The next scene, I am in a break room or cafeteria type place and this really good-looking guy is watching a local (high school state tournament) boxing match on TV where a HS male buddy of mine his little bro was in the tournament on tv. His boxing gloves looked like white versions of those giant \"Incredible Hulk Fists\" that are a popular toy . I started watching and cheering the boy on, but the room kinda changed and I was in this unfamiliar room with a hardwood floor with this \"Maggie Kelly\", only she was Kate Winslet (who is , of course, beautiful), apparently she had been wearing a dark, messy-haired wig and plain clothes when I met her first. SO, I was like BFF with Kate Winslet and so happy mom had introduced us and a middle-aged male (Ihave never seen him before, but in the dream, he was a friend)came around the corner and he was weARIng a wig and the same outfit as Kate WInslet and looked like a mirror imagage of her. He ended up collapsing, I think he died, and I saw a tear trickle down Kate's cheek; she was so moved that this man had laid down his life for us.",
  isPublic: false,
  dreamType: 'Normal Dream',
  sleepStartHour: 22,
  sleepStartMinute: 22,
  sleepEndHour: 7,
  sleepEndMinute: 44,
  date: '2017-3-08',
  user_id: 2}, {title: 'Six Flags',
  content: "Alright just something to keep in mind, there are two groups of people involved in the first part. One group I used to be very close with but the friendship ended abruptly and badly, I will call them bobyX and jimmy X. The other I am friends with still, I will call them RickY and RobY. These two groups know eachother in real life. We were preparing to go to six flags, we are in a car picking people up. I am in a mini van with bobyX and jimmyX, RickY is driving. We are having a good time in the car and are excited. We arrive at RobY's house and there is some discrepency about space in the car. For some reason I stole or borrowed a seat from the car a few days ago but I don't tell them I did, this interfears with my ability to go with them as I tell them I will find a way there. I go to my grandfathers and get side tracked a bit with something or something like that or my car doesn't work, but they are on they're way or are at six flags and I am highly disappointed. I call bobyX and I ask should I still come, and he gives me this unconcerned response and he says it is not fun any more. I am still thinking about going and trying to find a way at this point. Now for some reason, I am in target (the store). I am walking through and there is an older woman manager there who is trying to get me to buy this clock or something of the sort. I tell her no but she is getting rude about it, so she says you'll buy it for sure now, then she puts these price tag stickers on my back, and for some reason that it supposed to implicate that I was trying to steal it. A cop shows up and talks to her, she tells him I was trying to steal it. He gives me a look at first like he is considering that it's true, but then looks at her and says 'how would he have known the price of it?' Or something like that, as to say that he thought she was lying. Then she runs away. Now I am trying to leave because I am still either expecting a call from bobyX or that I want to go call him about going to six flags. I start walking out of target and the same cop stops me for some reason, and he's like 'no no, come on here with me'. He is now trying to get me to put out or put away these Christmas decorations on the shelves in target. I try to explain to him that I don't work here but he won't have it. Then I try to tell him that I donate to charity every month but I stop my self because I remember I didn't for the last two months. Either way I just run away and get outside. I start thinking about six flags again and driving there, but then I remember that I would have had to pay to go there and I just don't care about going anymore and I am no longer concerned about it. Okay now this is the second part of the dream, I feel like I was half awake for this. For some reason, in a dream state I am rethinking about the woman with who tried to frame me at target but I am thinking of it in a different context and aware that I am watching it happen and also narrating it. I am watching myself in an ocean making out with some girl. We both dive under water at separate spots and I see the woman who framed me but now she is a different better looking person and I go make out with her now instead. I feel like I remember the other girl being upset about it. That's the end of the dream.",
  isPublic: false,
  dreamType: 'Nightmare',
  sleepStartHour: 21,
  sleepStartMinute: 4,
  sleepEndHour: 9,
  sleepEndMinute: 13,
  date: '2017-3-09',
  user_id: 2}, {title: 'Evil Man',
  content: "There's this presence of a man, tall and dark, the only detail I can see is that he's got a hat on. I can't tell anything else about him, I can't look directly at him. All I see is his dark shape. I can see he's there, and feel his presence. He's mean, I can tell that much. He never moves, just stands there, he's just...with me. I've seen him standing in the doorway to my room as a child. Seen him a more back then, a few times in my adulthood. I haven't seen him or thought of him in over a year. Then the night before last I dreamed of him. I was in the car, front seat, with my husband driving. I was holding our brand new baby in my arms. The man was to my right. We were driving fast on this big highway, and it was like a scene from Final Destination. Cars and trucks were crashing into each other, construction sites were blowing up, we sped past it, avoiding being crashed into or hit with anything. We finally made it past it all....only to end up driving off the road like it was a broken or unfinished bridge. We flew through the air, and slowly everything disappeared. My husband, the car, the man. It was me and my baby.... Falling. The air was lifting him out of my arms and I graves onto him so tightly and told him how sorry I was, and how much I loved him. Then....it all stopped. I woke up for a second....I swear my heart had stopped. I was petrified. I had to make sure my baby was still breathing! Then before I knew it I was in this place, I had never seen before. There were rooms, with people I don't like living in them. I couldn't leave, I was like a prisoner there. The man was the boss, I felt like he owned me. I felt like his slave. I had a job to do and idk what it was supposed to be, I just knew I should have been doing something. He was there and I was terrified. My family was gone...I remembered us dying...my older son wasn't even in the dream. But I missed my family. I knew I was being kept from them....I was owned by this man.",
  isPublic: false,
  dreamType: 'Nightmare',
  sleepStartHour: 19,
  sleepStartMinute: 58,
  sleepEndHour: 5,
  sleepEndMinute: 27,
  date: '2017-3-10',
  user_id: 2}, {title: 'Pink Sky',
  content: 'So i start off in a coastal town i grew up close to called asbury park (this place is known for being pretty dangerous even if the towns around it arent). It is night time, and i am inside a house. Im here trying to steal stuff (dont do this in real life but i do go in abandoned houses although i dont feel its connected), and i have a group of people in a car waiting for me outside. Im walking around the house anxious but actually taking anything, so eventually i decide im cutting it too close and decide to leave. As im leaving i try to close the door but the lock is turned open so its stops the door from closing. I notice it but decide it would take too long to fix? So i walk out of the house but i leave by myself no one is involved anymore. I am walking hastily down the street because i know i was just illegally inside a house and i know i am in a potentially violent neighborhood. I turn the corner and i see a group of people walking outside of their house across the street. I immediately get scared and i quickly come up with the brilliant idea to take my shoe off and throw it in the distance thinking that they will chase it because they are trying to steal from me. They then start running towards the shoe, but i realize they were just out for a job (wtf). I then cut through someones back yard, it may have had a maze like feel to it but i cant exactly remember. Its day light/late evening now and i am walking towards the board walk, on the boardwalk is a party/festival with rides and attractions. So there are alot of people there but most of them are people i only partially know, like not anyone i am or have been good friends with but people that are just familiar to me or ive known through other people. I talk for a short period of time then i feel like leaving, i start heading one block up from the board walk onto this field like place with a couple trees (real place in asbury). Now there is a big change, all of a sudden everything gets very beautiful and vibrant and almost has an anime feel to it. The sky turns a very vibrant sunset pink and the trees grow these flowers on them. Randomly now i am just with this girl. Her hair is pink just like the sky is, she is apparently my significant other and i like her very much. So im with her here kind of hanging out in this field and then i look up at the sky and everything is clouds but they are still pink, the clouds cover everything with no gaps and it has this weird ocean like texture to it as it starts waving. Im studying it trying to decide if the clouds are pink… and i woke up.',
  isPublic: true,
  dreamType: 'Lucid Dream',
  sleepStartHour: 23,
  sleepStartMinute: 5,
  sleepEndHour: 7,
  sleepEndMinute: 5,
  date: '2017-3-20',
  user_id: 1}, {title: 'Ogres and Chuck-E-Cheese',
  content: 'I was sitting in a building that kind looked like chuck-e-cheese, and outside there were these huge beasts called "ogres," they were invading the town. They were huge, humanoid creatures, they were all armed with mysterious hammers. If one sees you, it will chase after you until it has the chance to crush you under the weight of its hammer. They are each about as tall as a T-Rex. I do not remember any of their features. Anyways... the building looked abandoned, and there were people hiding under the tables, chairs, in the cabinets, etc. The bathroom was a multi-stalled, little room. I walked in to wash my hands, and a little boy (i was in a girls bathroom???), about three years old, walked out of one of the stalls. He washed his hands, but he couldn\'t reach the paper towel dispenser, so i handed him a bunch. Then, an ogre smashed its fist through the vent on the ceiling. It left a gaping hole, and it peered down into the bathroom to see what was causing all of the noise. I screamed and told the little boy to run, but he stood there in pure terror, and i ran for my life. I am assuming you know what happened to the little boy. (he got smashed) I ran outside, Pewds (aka Pewdiepie from YouTube) and Marzia (aka CutiepieMarzia from YouTube) were standing next to the doors. Marzia was crying because her pug Edgar got lost somewhere, and she was certain it couldn\'t survive on its own. I ran to the car and hid in the back seat, but the ogre could see me getting in the car so it smashed the car, as soon as i was crushed i woke up.',
  isPublic: true,
  dreamType: 'Lucid Dream',
  sleepStartHour: 21,
  sleepStartMinute: 44,
  sleepEndHour: 6,
  sleepEndMinute: 47,
  date: '2017-3-21',
  user_id: 2}, {title: 'Kim Kardashian singing Miranda Lambert songs',
  content: 'I looked like Kim Kardashian in my dream where I was to have a concert singing Miranda Lambert songs(I am not a singer in real life). First off, I couldn\'t find an outfit to wear for the concert and was late to the sound check. Once I get there I get my song list and am told I have time to go to the bathroom. On my way to the bathroom I see my mom and lots of other friendly faces I know all saying hello but I don\'t have time to talk to them so I just wave and continue running to the bathroom. Once I find the bathroom and finish using it I am running trying to get back to the stage which seems like I left forever ago. I am running but my legs can not move as fast as they should to get me back down to the stage on time. Suddenly I hear Kim Kardashian singing some sleazy song over the loud speaker, taking my place because I didn\'t get back in time to perform. Once I finally make it to the stage, I am told I can\'t perform because I took too long.  I woke up so angry!',
  isPublic: true,
  dreamType: 'Normal Dream',
  sleepStartHour: 24,
  sleepStartMinute: 14,
  sleepEndHour: 8,
  sleepEndMinute: 13,
  date: '2017-3-22',
  user_id: 2}, {title: 'Lottery',
  content: 'I was at a grocery store with my fiancé & her child. We left the store and was in the car. My fiancé asked me to take her loosing lottery tickets in. I realized she forgot to scratch one. Once I got in I scratched the ticket. I realized an infinity sign and kept scratching. To my immense shock we have won $300,000!! I was so surprised, shocked and dumbstruck … I was just so excited I started hugging the clerk.  After a few moments she did paperwork and printed out this receipt . This receipt was like 100 feet long and I had to sign multiple spots. I had to fold up this has thing and put it in my pocket, as I went back to the car I decided I wasn\'t gonna tell the fiancé yet.. I wanted to surprise her. They were upset that I was in the store so long because her son wanted to go to the park to play. She drove off and went to her parents house.. She went inside and came right back out. She said " don\'t you have something to tell me" hahaha  I started thinking it was on TV or something.. ',
  isPublic: true,
  dreamType: 'Normal Dream',
  sleepStartHour: 21,
  sleepStartMinute: 23,
  sleepEndHour: 6,
  sleepEndMinute: 15,
  date: '2017-3-23',
  user_id: 2}, {title: 'Disease and Old Folks',
  content: 'I had a dream this morning where I was going someplace and found myself in a kind of mall. I saw nothing to buy there, but it was a huge place, cavernous, high end, yet I saw no real place to buy anything. I went through to find a room, but was treated as if I was visiting for no charge, as if family were putting me up - surprising. I found myself sort of sharing a place with two elderly people who were bedridden, and so old as to be helpless and dependent. There were nurses and attendants for the whole place - which is bewildering based on how deserted it was. Suddenly more people were getting in which surprised me a lot. They just went in and out of the old peoples rooms, and seemed like they were uncaring, and only concerned with how they appeared as they looked something like a social PAC looking to control the facility. I felt surprised. I was startled by a stranger who popped up every now and then. i found that they knew where the elevator was. I followed them in but they only wanted to go down. I felt that might be a way out as the ground floor always has the entrance and exits. After I got in there was a male and female PAC member and the female raised the elevator door from the bottom of the elevator car, and then we went downward. I went out of the elevator to find I was in the basement which was like a shooting gallery to play such games in high end, very complete, and huge, like those games where you shoot something/someone and lights blink on and off rapidly while sound effects go off at decibels that might be too loud to hear conversation. NO one was there, i felt like something was going to pop out and surprise me out of no where. Then I went back to the elevator out of curiosity and those people were still there and one raised the door again. I then noticed that these two had some form of disease on their skin - i was shocked. It looked like large blisters that marked the skin in a kind of pattern as all blisters touched together. I looked at my right hand and saw that I had a little of it there on my palm. I was so shocked and surprised because I didn’t think I touched anyone. I felt startled and started to panic. Then I awoke.',
  isPublic: true,
  dreamType: 'Nightmare',
  sleepStartHour: 22,
  sleepStartMinute: 11,
  sleepEndHour: 10,
  sleepEndMinute: 1,
  date: '2017-3-24',
  user_id: 2}, {title: 'Live From The Muppet Show',
  content: 'I was a child and my mom, my dog Sophie, and I were going to a live tapping of The Muppet Show. For some reason Sophie was in a baby carriage and my mom was treating her as a human infant. The crew was still setting things up and we went backstage.  There we saw Jim Henson. He was busy but upon noticing us standing there he approached us happily and greeted us. He then took notice of my stuffed dog, Russell, who I was carrying around.  "Well now, who is this?" He asked "His name\'s Russell."  He noticed the hole in the back of Russell\'s head and asked to hold him. "He\'s a puppet!" He stuck his hand into the hole and moved Russell\'s mouth in wonder "Ah! He\'s actually a simple thing." He moved Russell\'s mouth to my cheek and had him give me a kiss. I giggled. I was so happy to meet Jim and he\'d taken such a shine to Russell.  He handed me back Russell and said he hopped we enjoyed tonight\'s performance.',
  isPublic: true,
  dreamType: 'Normal Dream',
  sleepStartHour: 23,
  sleepStartMinute: 1,
  sleepEndHour: 8,
  sleepEndMinute: 25,
  date: '2017-3-25',
  user_id: 2}, {title: 'Bulls, Dogs and Annoyance',
  content: 'Two dogs (both dark colors) were growling at me and giving me all the warning signs that they were going to attack me. I remember not really caring and taunted them because I felt aggressive. When the black dog lunged at me, I was able to stop it from biting me and I held it until someone came and saved me. I remember feeling furious about being attacked. Then I was in a backyard and my two cats in real life were appearing as Labrador retrievers in the dream. Both of the dogs got a hold of white rabbits and were killing them. I shouted, telling them to stop but I was also getting so angry and mad about my clothes - which were  splattered with blood. Later I was telling someone about how i felt so much anger at the time. All of a sudden, cows were appearing and I started feeling angry - i didn’t want to see more animals. A bull sees us and walks towards me and starts nudging me in my back with his horns and was causing some pressure. I felt so furious by this point I screamed. Angrily, I stormed off and sat on a bench. I was fuming. Then I woke up.',
  isPublic: true,
  dreamType: 'Nightmare',
  sleepStartHour: 20,
  sleepStartMinute: 6,
  sleepEndHour: 9,
  sleepEndMinute: 4,
  date: '2017-3-26',
  user_id: 1}, {title: 'Tornado and more …',
  content: 'I\'m in a room in someone else\'s house. With me is my 11 year old sister and my fiancé. My fiancé, who is closer to windows, tells me there\'s a tornado headed directly for us. I have us assume the tornado drill positions they have you practice in school, taking my position over my sister to make sure she has an extra level of protection from debris. We hear the storm getting really close, then starting to fade. I remember this person has a basement. We run for it. When we start to go down the stairs, I see there are feral cats scavenging through stuff and they start to run and hide. I know there\'s something else down here. Later in the dream, that would be confirmed as I saw creatures with blind eyes, wide jaws, and extremely sharp teeth.',
  isPublic: true,
  dreamType: 'Nightmare',
  sleepStartHour: 19,
  sleepStartMinute: 59,
  sleepEndHour: 5,
  sleepEndMinute: 8,
  date: '2017-3-27',
  user_id: 2}, {title: 'Dogs and Werewolves',
  content: 'I had a dream where I was visiting in a stranger’s house who two pet dogs.  didn\'t really see the owners at all which was weirdly eerie and odd, but the dogs were very active house pets, mid size or smaller, and I was able to get very close with the largest of them. But then I had to leave to go somewhere and found myself in a dark street with alleys and tall buildings all around - it was a really scary area and I felt myself getting fearful for my wellbeing. I was suddenly aware of two werewolves across the street. They were both standing on their feet like people do. One came very close in a threatening way, so I tried to speak "In the spirit" and said to it, as it began to get close enough to snarl and was threatening, which made me very scared, "Wolves! You know who Jesus Christ is as every molecule in your body vibrates to His name!" It was about to bite my face or neck or something, but paused, breathing it\'s hot breath in my face, and the other one crossed the street to join the first, but they never did anything harmful, just frightened me so deeply. The wolves then ran in to the dark and I wandered by myself, still wary and very afraid. I felt my heart beating in my dream and was terrified to the core. I remember tripping on something, panicking and falling … Then I woke up in cold sweat, still scared and petrified out of my mind.',
  isPublic: true,
  dreamType: 'Nightmare',
  sleepStartHour: 21,
  sleepStartMinute: 32,
  sleepEndHour: 6,
  sleepEndMinute: 59,
  date: '2017-3-28',
  user_id: 2}, {title: 'Alligators and Eggs',
  content: 'I dreamt about dozens of baby alligators and there were dozens of chicken eggs. There were coming out from earth n when I try to get near to them, they were going down again. Eggs were all piled up in one place n when I got near to the eggs baby alligators took it one by one n hurriedly escaping back to underground as if they were their own eggs. Some cracked their eggs so I felt like I was scaring them so I backed up. I also dreamed of swimming in river or lake. Normally I can\'t swim well and kinda scared of deep water but as soon as I dive in It felt like some gentle force helped me to stay afloat',
  isPublic: true,
  dreamType: 'Nightmare',
  sleepStartHour: 23,
  sleepStartMinute: 12,
  sleepEndHour: 8,
  sleepEndMinute: 48,
  date: '2017-3-29',
  user_id: 4}], dream => db.model('dreams').create(dream))







db.didSync
  .then(() => db.sync({force: true}))
  .then(seedUsers)
  .then(users => console.log(`Seeded ${users.length} users OK`))
  .then(seedDreams)
  .then(dreams => console.log(`Seeded ${dreams.length} dreams OK`))
  .catch(error => console.error(error))
  .finally(() => db.close())
