const db = require('APP/db')

const seedUsers = () => db.Promise.map([
  {name: 'so many', email: 'god@example.com', password: '1234', averageSleep: 8},
  {name: 'Barack Obama', email: 'barack@example.gov', password: '1234', averageSleep: 6},
  {name: 'Chloe Hwang', email: 'chloe@example.gov', password: '1234', averageSleep: 7},
  {name: 'Laura Jeong', email: 'laura@example.gov', password: '1234', averageSleep: 7.5},
  {name: 'Aly Khaya', email: 'aly@example.gov', password: '1234', averageSleep: 8.3}
], user => db.model('users').create(user))


const seedDreams = () => db.Promise.map([
  {title: 'A Bad Dream',
  content: 'Pictures that can’t be described\nDance in the brilliance\nFor you will never be outnumbered\nA celestial body enters\nHope will show you\nHorizons of magnificence\nBecome what is',
  isPublic: true,
  dreamType: 'Lucid Dream',
  sleepStartHour: 23,
  sleepStartMinute: 59,
  sleepEndHour: 7,
  sleepEndMinute: 59,
  date: '2017-3-16',
  user_id: 1},
   {title: 'Reconciling with Ex',
  content: "In the dream, I was in my living room and I looked out the window and it was cloudy. I saw that my ex moved in with a couple of things and he told me how he lied he was going to be homeless so my tenants upstairs decided for him to move in with them. I was so angry. He was wearing white shirt and gray pants. He was also walking bare feet in the house. So I ran into my dad who was in my kitchen. He's cooking soup. He said its for my ex and I told him my ex is stalking me. All of the sudden my ex broken my ceiling and I can see him standing above. He's telling me how angry he was to see me out with my boyfriend and how he watched me had sex. He said how it kills him to hear me moan. So I freaked out. I went upstairs and it was empty but I told my tenants not to believe him but they think I'm rude. Now, I am pulling him out and he refused to move. I cried and told my dad. All of the sudden we are at his job building. Now, I am pulling him out and he refused to move. I cried and told my dad. All of the sudden we are at his job building. He told me I'd be safe in here. I asked him how long do I have to hide in here. When I went back to my house, my ex tampered with my medication and my dads. I started to tell my mom I'm not taking my medication. I freaked out. I was going to call my boyfriend but it felt like he was far from reach. I didn't want him to be angry either. I felt like my mom and dad was no help. I had to try to pull my ex out. So I told my ex to come out right now. He came down the stairs shouting. My head started to hurt. He's cursing me out. He brought down a plastic dish. Then wore his flip flops by the door (now I remember I got flip flops by the door that my bf got me). I told my ex to get out. He was stubborn to leave. I got mad and he got even madder. I try to push him out and he won't leave. I was so terrorized. When I almost got him out the door, I woke up with neck pains and headaches.",
  isPublic: true,
  dreamType: 'Normal Dream',
  sleepStartHour: 22,
  sleepStartMinute: 23,
  sleepEndHour: 6,
  sleepEndMinute: 39,
  date: '2017-3-17',
  user_id: 1},
   {title: 'Hurt Dogs',
  content: "The first night my dog Scarlett was in my yard and there was a bonfire. There was barbed wire around the fire so no one would get too close. Scarlett became entangled in the barbed wire and caught fire. I went to help her. My other dog Stella got in my way so I shoved her away and it broke her leg. Both dogs seemed okay and I woke up but I was upset. Tonight a friend and I were in my yard and opened the gate to leave, Scarlett ran into the front yard and we chased her to get a leash on her. She then ran into the main road as I called for her to stop. Stella followed her and they ran through an intersection. Scarlett made it past the cars but Stella was hit very hard. She walked back to me and I woke up and cried.",
  isPublic: true,
  dreamType: 'Nightmare',
  sleepStartHour: 21,
  sleepStartMinute: 59,
  sleepEndHour: 7,
  sleepEndMinute: 9,
  date: '2017-3-18',
  user_id: 1},
   {title: 'Smoke/Summer/Beach',
  content: 'I saw that I was inside a house with others. I could see from the window the sea and the sunny sky. Then further away I saw lot of smoke (probably coming out of a building). It filled the sky. It was dark brown and dense. The smoke was coming towards us. We saw it and stayed in. I could also see a helicopter above the sea but flying very low because of the smoke. The smoke covered the place now. I was holding my mobile in case it would get very dark so I could use it for light in case I would get scared of the dark. But the smoke lasted only for seconds. It left us. The sky was clear now. There was a lot of light from the sun now. It was day time and summer. The helicopter landed on the sea but in the shallow water. Now I saw myself walking on the beach wearing my white swimsuit. I was relaxed. I noticed that there was some sand on my body. And I think I was barefoot.',
  isPublic: true,
  dreamType: 'Normal Dream',
  sleepStartHour: 23,
  sleepStartMinute: 2,
  sleepEndHour: 7,
  sleepEndMinute: 40,
  date: '2017-3-19',
  user_id: 1},
  {title: 'Carnival of Terror',
  content: 'I dreamt I was at a carnival/fair type of place. I was hanging out with friends, I remember anon and anon 2 being with me. The tip of my left index finger was bothering me, one time I looked down and saw something grey sticking out of it. The grey object began to grow out of my finger, it looked like a piece of pencil led for a mechanical pencil. I remember feeling pain as this was happening. After about an inch of it grew out of my finger it fell off, this was followed by a bunch of yellow tinged puss pouring out the exit hole that the grey object created. Pain was still relevant. After about a minute it stopped. I cleaned up my finger and headed toward a line of people. Following the line I ended up in a dance/concert type of event where I saw anon 3 and anon 4. Two people I never see, one I haven’t seen in years. I left the place after someone tried getting me to dance and I wouldn’t.',
  isPublic: false,
  dreamType: 'Nightmare',
  sleepStartHour: 20,
  sleepStartMinute: 49,
  sleepEndHour: 8,
  sleepEndMinute: 8,
  date: '2017-1-02',
  user_id: 1},
  {title: 'Peach Creature',
  content: "The creature I am seeing has peach colored skin, is bald, and it’s back legs fold inward at the knees. It uses them as sort of a catapult which enables it to launch itself long distances in a single bound. It’s face is demonic looking with small eyes, a wide stretching mouth with big jagged looking teeth. The scenery is a glowing red in the night sky, I am in a village with no lights anywhere to be seen. The creature enters the village.. the next thing I remember is seeing a baby held within the creatures short front legs. The creature then continues going to every house in the village and repeating this till every baby in the village has perished, the creature stained blood red when finished. After this, I remember perceiving the village as if I were laying down on the ground outside, on my back staring into the red night sky. A woman walks into my view.",
  isPublic: false,
  dreamType: 'Nightmare',
  sleepStartHour: 23,
  sleepStartMinute: 1,
  sleepEndHour: 8,
  sleepEndMinute: 31,
  date: '2016-12-14',
  user_id: 2},
   {title: 'Shopping at Satan\'s Jewelry Store',
  content: "I am back in East Liverpool, and am visiting Calcutta, where all the better stores are. I see a well lit store, neon on the front, and sparkling of many colors inside of the store. I walk inside out of curiosity. What is Satan selling these days? Is it actual Satanism, or some kind of fad of dark imagery? The sign out front, said in bright blue and pink lettering, “Satanism Store”. I look around and see display cases of sparking jewelry made of precious stones of all colors. I catch a partial glimpse of a pentagram hidden behind a display case. All in all, it seems like a mix of high end jewelry store and some kind of hand metal craft of metal jewelry with different bold designs that seem ancient pagan inspired. I walk pass the jewelry. I believe it is unaffordable, but I do not see any prices. and I am not interested in Satanism, the sparkling jewelry, was some how Satanic, but not openly Satanic, but is jewelry crafted by Satanists for other Satanists. An elderly lady comes up to me and says “I know just what you are looking for, come, let me show what we have back here” She leads me a small shelf full of Mary statues. They look like the miniature versions of the Mary statue at the church I attend. She then shows me a beautiful collection of polished stones: all colors of onyx, there's periodot (green), green aventine, colors of blue, orange, and red. She says, 'See all these beautiful natural stones?' She points out one flat, polished, blue white stone on display she says, 'but this is your stone, because you have Native American blood from which you get your psychic abilities from flowing through your veins.' That stone, I realize must be celestite.",
  isPublic: true,
  dreamType: 'Normal Dream',
  sleepStartHour: 21,
  sleepStartMinute: 59,
  sleepEndHour: 7,
  sleepEndMinute: 9,
  date: '2017-3-18',
  user_id: 2},
   {title: 'Queen\'s Sister',
  content: "I saw that I wanted to paint the gate doors of my house. I was supposed to be a queen even though I was no different than I usually am (clothes or appearance or time). Two men were instructing me how to do it. I was holding a brush and I was just using water to practice. I noticed some dust while doing it. They said that I would need help because I have a busy life and did not have a lot of time to do it. I was looking at the gate doors and I thought that they were't big and I could paint them on my own. I could finish in a couple of hours. The color I wanted to paint them was dark blue. Navy blue I guess. The present color is grey and I wanted to refresh it with the blue. Then I was told that my sister who was also Queen (but I was in charge) would not help cause she thought qeens do not do this kind of things. I told them to tell her to come. I saw her coming down from the stairs to me. She was wearing a dress of old age (victorian I guess). She also had a mustache. I did not comment her mustache even though I've noticed it. I told her to paint with me the door gates and work is not a shame. It doesn't matter if we are queens or not. She said that the reason she was not helping was because the gates are wet cause it rained and need to dry first. I looked at them and she was right, they were wet, but I did not admit it and said maybe we can put the primer first. Somehow I wanted her to stay just in case she was trying to find excuses. I also feel that I was in a hurry to start. Someone has already put blue paint on them but it was unfinished and I was asking who did it. I think it was a child. A boy... That's all I remember even though the dream did not finish there.",
  isPublic: true,
  dreamType: 'Normal Dream',
  sleepStartHour: 23,
  sleepStartMinute: 2,
  sleepEndHour: 7,
  sleepEndMinute: 40,
  date: '2017-3-19',
  user_id: 2},
  {title: 'Death Warning',
  content: "So I had a few dream of the world ending and as I gathered my family to take them to a safe place I found myself frantically looking for my older brother to take him with us when we all finally make it to a safe place my a big wave comes and takes my little brother away and I try so hard to save him and I can't my other dreams are similar end of the world scenario but in my dreams my little brothers family are in my dreams and although I'm very close to my little brother i do not have a good relationship with his father or his family and we do not comunícate .....sadly my little brother just passed away very unexpected and I am wondering why before it happened I kept having all those dreams it's not the first time I dream of things or people and have things happen ....I am actually worried because I am now having dreams of being in car accident or seeing car accidents and last night I had a dream of being cought in a storm while hosting a party but I had a very uneasy feeling in my dream and I've had that same feeling all day",
  isPublic: false,
  dreamType: 'Nightmare',
  sleepStartHour: 20,
  sleepStartMinute: 49,
  sleepEndHour: 8,
  sleepEndMinute: 8,
  date: '2017-1-02',
  user_id: 2},
  {title: 'Swimming Away from Albino Python',
  content: "So I was at the Sunshine Coast with a dream friend or two. The city was extremely modern and spacious. There appeared a man made beach with the edge being one step in with the water level unknown. The step made of a common grey speckled bricks with newer houses. I walk along it looking for a good place to enter the water. After a long walk the brick turns to a natural sand. There is more people there some I knew from high school. The atmosphere is overall friendly. not long into the water is a smallish round sand island. I enter the water and swim around there are a few others there. I start to get more slightly to the side of the island because of a current but every thing is fine. After a little while I see two albino diamond pythons half submerged in the water and their heads resting on the slop of the island. I go to stand up in the water however my foot touches a albino diamond python that I can't see and I instantly raise my feet and swim a bit to avoid being bitten. I try again futher down the current but there are more pythons under the water everywhere. My only option is to allow the current to take me to the back half of the island but I don't want to go to the back of the Island and panic. I start to swim frantically towards the island however at this point the current is to strong and I'm not getting closer to the island. So I relax and keep paddling lightly. The sand behind me, the shore line, turns to a dark brown rocky pebble an older style like in brisbane. At half way a long the side of the island I see a short small round edge on the shore line. I reach for it and climb onto it. I need to get to the island and if I dive for it I could under dive and be taken by the current again or I could over dive and hurt myself in hitting the sand. I plan to dive with my face more upwards as to hopefully avoid injury. I do this and successfully reach the island with no problems. There is a crowd still on the island, it is once again a friendly and sunny atmosphere.",
  isPublic: false,
  dreamType: 'Normal Dream',
  sleepStartHour: 20,
  sleepStartMinute: 49,
  sleepEndHour: 8,
  sleepEndMinute: 8,
  date: '2017-1-02',
  user_id: 3},
  {title: 'Ancient Ancestor',
  content: "I was in my room at dads house. Dad had left to go get paint in the morning and so my brother and I were home alone getting ready for school I think. I was in my room, sitting on the bed and my door was open wide, when I felt like someone was watching me. When I couldn't shake the feeling, I went to pierces room to ask him about it and he said he was fine, but then everything changed and I heard the voice of a ghost, it was the one I felt watching me in the hallway. She was African with really dark skin and moldy yellow teeth and knappy hair. She wore a raggedy white dress and i could only see and hear her at this point. Pierce had no idea what was going on. She said she had something important to tell me that couldnt wait and she insisted on being near pierce and touching him. Pierce had no idea what was going on as only I could see and hear her. Suddenly she touched pierce and I saw her for the first time in her physical form. I knew she was in pierces body but I saw her as a dark black woman in a raggedy white dress. She had short knappy hair and her teeth were rotten. She was angry she said and she wanted something. Suddenly it got almost pitch black in the room save for a projection of black people dying from slavery. I think she wanted revenge for it and she told me she need me. I got worried and tried to get her out of Pierces body but she just laughed and said it wouldn't work. She was a witch in her life and this made her a more powerful ghost apparently. Then she disappeared with pierces body as das came home and so I was alone. I tried telling dad but I was crying super hard and he didn't believe me. Then I woke up after saying I needed to tell my friends at school. ",
  isPublic: false,
  dreamType: 'Nightmare',
  sleepStartHour: 23,
  sleepStartMinute: 1,
  sleepEndHour: 8,
  sleepEndMinute: 31,
  date: '2016-12-14',
  user_id: 3},
   {title: 'Shopping at Satan\'s Jewelry Store',
  content: "i dreamt i was in a highly modified version of my home, it had a shrunken version of my hospital workspace inside of it along with a selection of other employees that i could have known in the distant past. a few of 'em were supervisory but relatively kind, and they tried to help me de-clutter my hopelessly cluttered place, except for one spot in the beginning of a hallway where there were electrical wires of some kind blocking me from traversing without hopping over them. i had a large metal cart of some kind filled with some kind of supplies i was to move from a bedroom into the living room, and i could only move the cart over to where the wires were, then unload it there, or it could have been i was to take clutter from the living room into the cart then shove it down the hallway and unload it into the bedroom. i went down the hall to the bedroom when a bee came out of nowhere and started harassing me, chasing me back and forth, and i picked up a white tennis shoe and started ineptly swinging at it trying to get it to flee, and missed each time until the final time where i swatted it good where its stinger was, and it mysteriously shattered into zillions of glittery sparkly pieces with a loud glass-shattering ZAP! then what was left of it instantly turned into a beautiful petite blonde beauty queen, who waved her finger at me  :nodding: and said \"what did you do that to me for?\" \"i want you to tell me, IN FRENCH, what you just did to me!\" and i struggled with my rudimentary french to try to grab a suitable word and only feebly came up with \"vomir\" [infinitive form of the verb meaning \"to vomit\"]. she laughed at me the way a pedantic french teacher might derisively laugh at a slow french student. but she was BEAUTIFUL!!! gorgeous, wearing light blue designer jeans and a white lace top. ice-blue eyes, angelic face which mop of blonde ringlets framed most alluringly. she then said, after some flirtation, \"all is forgiven, but first i need to find out how you really feel about me, let's have sex.\" then the dream jarringly segued into another scene where i was discussing fascism with an englishman. then i awoke.",
  isPublic: true,
  dreamType: 'Normal Dream',
  sleepStartHour: 21,
  sleepStartMinute: 59,
  sleepEndHour: 7,
  sleepEndMinute: 9,
  date: '2017-3-18',
  user_id: 3},
   {title: 'Invisible Creature',
  content: "I was in my house (a mix of 3-4 different real-life houses), I was at the kitchen stove. I was getting ready to cook something. Noticed plants were in oven. I heard a noise. Water running out of the sink faucet. Something invisible turned it back off. They moved a container holding utensils. Lifted a huge knife. Attempted to stab me in my neck. I screamed for my mom to help me. She was busy. Kept begging. (misunderstanding for some reason). I begged a few more times. She said she would be there in a few minutes. Invisible \"creature\" was way too strong. My strength failed. I was stabbed. (I made the blade hit slightly lower) Wound wasn't as bad as it could've been. I kicked the invisible creature backwards and ran into the room my mom was in. She was horrified to see the knife. I sarcastically thanked her for helping me. Told her to pull the knife out. I wrapped a towel tightly around my neck to stop bleeding. I could hear the creature coming. Told my mom we had to get out of the house. We ran outside, past our vehicles. Told her to take the car. She said it is better to run on foot. I had no shoes or socks on. Snow was on the ground. Severe frostbite and my feet stuck to the sidewalk and roadway as we ran (extremely painful) told her I had no shoes on. Had to warn my dad and two other family members to stay out of the house. Terrifying black shadowy creature stood in the doorway when I went back to the house. Then I realized it was just the lighting. It was one of my family members. I tried to warn them to stay outside, but they didn't. Followed them in. I found my dad and other family member already inside. I begged them to leave the house. Told them it was too dangerous to stay there. They refused. I knew I would have to leave them there. I believe I prayed for their safety and then I woke-up. ",
  isPublic: true,
  dreamType: 'Normal Dream',
  sleepStartHour: 23,
  sleepStartMinute: 2,
  sleepEndHour: 7,
  sleepEndMinute: 40,
  date: '2017-3-19',
  user_id: 3},
  {title: 'Friend Who Passed',
  content: "My friend Eli died 12 years ago when I was 14. He was a very happy, goofy, loving person. He always got picked on in school because he was kind of nerdy. He died suddenly and unexpectedly. The day he died he asked me if I wanted to come over and play video games, I said no, let’s do it tomorrow. I was tired. So I never got to go play with him and have always felt bad about it. I have not thought of Eli for a while, until last night when I dreamt this: Eli was still alive, and then he died. I felt very sad and cried really hard for a long time. He then came back to life, but only I could see him. He took me on a strange vacation. We were walking through this beautiful, bright, tropical place, with amazing plants I have never seen. There was a large cliff/wall and we both almost fell over it and were hanging on the edge, when someone saved us. And we kept walking through this tropical wonderland. When we arrived at our intended destination it was an underground hotel without any windows. We were told we had to shower before entering the hotel.and that once inside we would not be allowed to leave for 4 days. I was frightened by this and felt claustrophobic about being locked in an underground building. I said I didn’t want to go in there. Then I woke up. Feeling sadness and confusions. What does any of this mean?",
  isPublic: false,
  dreamType: 'Nightmare',
  sleepStartHour: 20,
  sleepStartMinute: 49,
  sleepEndHour: 8,
  sleepEndMinute: 8,
  date: '2017-1-02',
  user_id: 3},
  {title: 'Being Chased',
  content: "A really scary human with claws and sharp teeth was coming after me. She looked exactly like me, except for black hair and creepiness. She was wearing all black. I knew I was dreaming but was too terrified to face her. Although I initially attempted to ask her who she was. She screamed & charged towards me. Much later, I found this other girl in the bathroom. She also looked like me, but she had black hair. I told her I forgive her for some reason. She told me that was a lie. I admitted it and told her if it was someone else they would be forgiven. However, since you ARE me, I don't. She said she knows. I apologized for interrupting her. Wanted to know who and why the scary girl was after me before I woke-up. She was upset I interrupted her, & acted like she had no clue who I was talking about. For some reason, I mentioned the grudge. (Haven't watched any scary movies in YEARS though) Then she finally realized who I meant. She was getting ready to tell me, but I woke up anyway. What might that be about?",
  isPublic: false,
  dreamType: 'Nightmare',
  sleepStartHour: 20,
  sleepStartMinute: 49,
  sleepEndHour: 8,
  sleepEndMinute: 8,
  date: '2017-1-02',
  user_id: 1},
  {title: 'Crushing',
  content: "So everyone is \"Shipping\" me with this person, and I am not really sure if I like them or not. We are good friends and all, and about 3 weeks ago i had a \"good\" dream about them, though i can not remember it. THese past 3 nights I have had bad dreams. Last nights, I was house sitting with two others, when we got inside the house, Drake and Josh (yes) was swimming in the pool. They tried to basically run, but for some reason i tried to fight them. Then it was girls fighting us, and then they left when I called 911. 911 arrived and it was like a bunch of people. I was then told it was the person i am friends with in real life, and glare at him. He glares back, and says something like \"I never liked you\" and then I woke up. The night before was where we moved, but the dream didn't start until we were exploring our new town. My mom was not in the dream, but my other family was. THe ground was flat. I guess I was happy, until I saw this lap pool and remembered all my friends and the guy i am shipped with and got really sad (I am on a swim team, so lap pool makes sense). I usually don't ever have dreams so I find it kind of odd i have been in these past few days, especially all bad dreams, about this person.",
  isPublic: true,
  dreamType: 'Normal Dream',
  sleepStartHour: 20,
  sleepStartMinute: 49,
  sleepEndHour: 8,
  sleepEndMinute: 8,
  date: '2017-1-02',
  user_id: 1},
], dream => db.model('dreams').create(dream))







db.didSync
  .then(() => db.sync({force: true}))
  .then(seedUsers)
  .then(users => console.log(`Seeded ${users.length} users OK`))
  .then(seedDreams)
  .then(dreams => console.log(`Seeded ${dreams.length} dreams OK`))
  .catch(error => console.error(error))
  .finally(() => db.close())
